version: '3'
services:
  nuxt:
    container_name: client
    build: ./docker/nuxt
    ports:
      - 9000:3000
    volumes:
      - ./src:/workspace
    working_dir: /workspace
    command: yarn run dev
  go:
    container_name: api
    build:
      context: ./docker/go
      dockerfile: Dockerfile
    working_dir: /api
    volumes:
      - ./api:/api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    tty: true
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local