version: '3'
services:
  nuxt:
    container_name: client
    build: ./docker/nuxt
    ports:
      - 9000:3000
    volumes:
      - ./src:/workspace
    working_dir: /workspace
    command: yarn run dev
  go:
    container_name: api
    build:
      context: ./docker/go
      dockerfile: Dockerfile
    working_dir: /api
    volumes:
      - ./api:/api
    ports:
      - "8080:8080"
    tty: true
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - TEST_DB_HOST=test-db
      - TEST_DB_PORT=5431
      - TEST_DB_USER=postgres
      - TEST_DB_PASSWORD=postgres
      - TEST_DB_NAME=test
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/postgres-init:/docker-entrypoint-initdb.d
  test-db:
    container_name: test-db
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5431:5431'
    volumes: 
      - test-db:/var/lib/postgresql/data
      - ./test-db/postgres-init:/docker-entrypoint-initdb.d
volumes:
  db:
    driver: local
  test-db:
    driver: local